# This file was automatically generated by SWIG
package RNA;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package RNA;
bootstrap RNA;
var_RNA_init();
package RNA;
@EXPORT = qw( );
1;
